### ISSUE TITLE
Custom HTTP Headers in REST API call

### ISSUE THREAD

**Issue by CGBassPlayer** [riok/Kreya#101]
**Is your feature request related to a problem? Please describe.**
APIs I work with have custom HTTP headers that are used to authenticate their service. When trying to use these custom headers and making a request, I get `The header ' client_id: <header_value_here>' is invalid.` and the request won't go through.

**Describe the solution you'd like**
Ability to use custom HTTP headers in requests

**Describe alternatives you've considered**
I didn't see anything in the documentation that would work around this

**Additional context**
I do not have any input into the APIs I am working against so I have to have custom HTTP headers. Outside of this limitation, I think Kreya is a nice application and I would like to continue trying it out.

**Comment by CommonGuy** [comment]
You receive the message `The header ' client_id: <header_value_here>' is invalid.` because your header does not conform to the HTTP standard. From the message, it looks like you have a leading space before `client_id`? Does removing that space resolve your issue?

**Comment by CGBassPlayer** [comment]
Looks like you were right. I guess when I copied their spec into the environment setup, there was a space. Curiously enough, there was not a space when looking at the inherited entries in the view for the call itself.

Here are some screenshots to show what I mean:

Headers in default settings with the offending space
![Environment Headers](https://user-images.githubusercontent.com/34293941/185937646-fb7617bc-a337-4fc2-aaa4-94a79a96bf81.png)

Inherited headers not showing a space
![API Call Headers](https://user-images.githubusercontent.com/34293941/185937452-e2832f3c-452f-420a-b053-dc10551ec47c.png)

I wouldn't necessarily call this a full on bug, but just something to watch out for. Thank you for the support!

**Comment by CommonGuy** [comment]
Thank you for your feedback, this can indeed be quite confusing. We'll implement a fix to show whitespace in the inherited entries correctly.
