### ISSUE TITLE
Kreya supports path base gRPC endpoints vs other tools

### ISSUE THREAD

**Issue by patkae** [riok/Kreya#105]
I was reading the feature comparisons: https://kreya.app/comparisons/bloomrpc/.

Since I did not see this there, I wanted to call out the fact that Kreya works with gRPC services hosted at a URL path (e.g. https://localhost;5000/user-svc/users.Directory/GetUsers), the `user-svc` segment is a path added to the service endpoint. Most if not all gRPC test tools do not support a pathbase for the gRPC endpoint.  This feature, whether it was intended or not, allows us to host gRPC services on the same port under different URL paths in kubernetes.

Microsoft has an implementation for gRPC dotnet clients to support the pathbase: https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#calling-grpc-services-hosted-in-a-sub-directory

And a github discussion on the topic is still open: https://github.com/grpc/grpc-dotnet/issues/880

So I do hope you guys keep this behavior.

**Comment by CommonGuy** [comment]
Yes, this is an intented feature and was requested here: https://github.com/riok/Kreya/issues/31.

We may need to add this to the feature comparison and documentation
