### ISSUE TITLE
Kreya always crashes on start on macOS 13.0 (Ventura)

### ISSUE THREAD

**Issue by mmac-m3a** [riok/Kreya#115]
**Describe the bug**
Kreya crashes on start (crash report attached). It does not even create any log file (~/.config/Kreya/kreya.log does not exist).

**To Reproduce**
1. start Kreya
2. wait for crash report

**Expected behavior**
Application starts.

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: macOS 13.0 on MacBook M1 Pro (2020)
 - Kreya Version: 1.8.1? Freshly downloaded from https://stable-downloads.kreya.app/Kreya-macos-arm64.zip

**Additional context**
Kreya was crashing pretty frequently also on macOS 12.6, but it was mostly usable. Now it is unfortunately entirely unusable :-/.

ZIP checksum matches:
```cmdline
❯ shasum -a 256 Kreya-macos-arm64.zip
ebabbf6ed470d0e6f660d1e0d92b1d4617e510dd6500166002cb839d91c0f034  Kreya-macos-arm64.zip
```
[kreya_crash_report.txt](https://github.com/riok/Kreya/files/9925700/kreya_crash_report.txt)

**Comment by mmac-m3a** [comment]
I guess, I've just created a duplicate of https://github.com/riok/Kreya/issues/111 :-(. Feel free to close/delete.

**Comment by CommonGuy** [comment]
Thanks for you bug report. We are closing this in favor of #111
