### ISSUE TITLE
After updating macOS to Ventura, kreya crashes immediately after start

### ISSUE THREAD

**Issue by harshvladha** [riok/Kreya#116]
**Describe the bug**
After updating macOS to Ventura, kreya crashes immediately after the start

It doesn't run for more than a minute.

**To Reproduce**
Use MacOS Ventura on M1 (ARM based)

**Expected behavior**
Doesn't crash

**Screenshots**
<img width="352" alt="Screenshot 2022-11-04 at 7 53 41 AM" src="https://user-images.githubusercontent.com/7391816/199871584-8ef1b14e-3653-4792-9079-1bac1a1e333e.png">

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: macOS Ventura 13.0 
 - Kreya Version : not able to read the version as it crashes immediately (I had downloaded a recent version after the crash became too often)

**Additional context**
Just updated macOS

I was planning to take the premium Kreya plan, but if it keeps crashing then there is no point. Even in previous macOS it used to crash as mentioned here - https://github.com/riok/Kreya/issues/97

**Comment by ni507** [comment]
Thanks for your report.
Several users have already had the error with macOS 13.0 which is tracked in the issue #111. Therefore I close this issue as duplicate.
We just released 1.9.0-alpha.3, which can be downloaded from https://alpha-downloads.kreya.app/Kreya-macos-arm64.zip. 
We will release a stable release soon if the tests are successful.
