### ISSUE TITLE
How do I find out the request headers in Kreya?

### ISSUE THREAD

**Issue by btfspace** [riok/Kreya#117]
I need to find out which headers Kreya sends when testing proto files

**Comment by CommonGuy** [comment]
Kreya currently does not display the sent headers anywhere. Kreya 1.9 sends these headers

- All headers as defined in the Metadata tab
- An `Authorization` header when an auth value has been selected (in the Auth tab)
- A static `user-agent` header, currently something in the form of `grpc-dotnet/2.48.0 (.NET 6.0.10; CLR 6.0.10; net6.0; windows; x64)` (though we will probably remove this in the future)

**Comment by fleytman** [comment]
> A static user-agent header, currently something in the form of grpc-dotnet/2.48.0 (.NET 6.0.10; CLR 6.0.10; net6.0; windows; x64) (though we will probably remove this in the future)

It's problem for my API

If i set in metadata User-Agent: "grpc-web-javascript/0.1" i get response header:
```grpc-dotnet/2.48.0 (.NET 6.0.4; CLR 6.0.4; net6.0; osx; x64) grpc-web-javascript/0.1```

**Comment by CommonGuy** [comment]
We released a fix for this on our alpha release channel. To use it, open the "About" window in Kreya and switch to the "Alpha" channel, then check for updates.

**Comment by CommonGuy** [comment]
The default user agent has been removed with Kreya 1.10
