### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by mirza-ali-ctct** [riok/Kreya#119]
**Describe the bug**
Blank window 

**To Reproduce**
1. Download the latest Mac OSx64 version.
2. Open the app
3. See the empty screen

**Expected behavior**
Application opens up with all options

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: [MacOS Catalina ]
 - Kreya Version [The version window is blank]

**Additional context**
Download link : https://stable-downloads.kreya.app/Kreya-macos-x64.zip

**Comment by CommonGuy** [comment]
Thanks for your bug report. This may be related to #112. We will look into this

**Comment by mirza-ali-ctct** [comment]
Can I download the previous version of the app. I am looking into the download section but cant find any way to download

**Comment by mirza-ali-ctct** [comment]
Licenses are displayed

**Comment by CommonGuy** [comment]
Thanks for verifying! I managed to reproduce the issue, but only when I have an invalid system language set.

Does the same apply to you? What is the content of the`$LANG`  environment variable on your system? And does launching Kreya via
```
LANG=en_US.UTF-8 kreya
```

work?

**Comment by mirza-ali-ctct** [comment]
```bash
echo $LANG
en_US.UTF-8
````

**Comment by CommonGuy** [comment]
We can reproduce this error on MacOS x64 and are working on a bugfix

**Comment by yiou362** [comment]
i have the same problem，empty scream，solve quickly pls

**Comment by CommonGuy** [comment]
We released a bugfix for this on our alpha release channel. The bug happens on older macos versions which do not support certain APIs.

You can download the newest alpha version from these links:

- For x64: https://alpha-downloads.kreya.app/Kreya-macos-x64.zip
- For arm64 (M1): https://alpha-downloads.kreya.app/Kreya-macos-arm64.zip

**Comment by CommonGuy** [comment]
This should be fixed in Kreya 1.10, which we just released.
