### ISSUE TITLE
Default settings for environment applies to all.

### ISSUE THREAD

**Issue by KamushekDev** [riok/Kreya#120]
**Describe the bug**
Default settings for environment applies to all regardless selected environment.

**To Reproduce**
1. Create project
2. Go to Project>Environments
3. Create Environment 1
4. Click Save
5. Create Environment 2
4. Click Save
5. Go to Project>Default settings
6. Select 1 environment
7. Click Endpoint
8. Enter some endpoint
9. Click save
10. Select "all environments"
11. Endpoint field contains our endpoint

**Expected behavior**
It should apply endpoint only for the 1 environment.

**Screenshots**
![Gif](https://i.imgur.com/xNmvAyN.gif)

**Environment (if possible, copy the information from the error dialog or the About menu):**
{
  "kreyaVersion": "1.9.0",
  "platform": "Win32",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42"
}

**Additional context**
It was working before.

**Comment by CommonGuy** [comment]
Thanks for your detailed bug report! We'll look into this, seems like a regression from previous releases...

**Comment by vlasovsv** [comment]
@CommonGuy As I see there is only one version  (1.9) is available to download. Is there any approach to get older version?

**Comment by CommonGuy** [comment]
We released a fix for this on our alpha release channel. To use it, open the "About" window in Kreya and switch to the "Alpha" channel, then check for updates.

**Comment by vlasovsv** [comment]
@CommonGuy Thank you very much! This is a great news.
