### ISSUE TITLE
Initialization failure when reconciling conflicting keys in env and user data

### ISSUE THREAD

**Issue by alee792** [riok/Kreya#123]
**Describe the bug**
If a project has JSON keys with the same name in both an environment and user data, Kreya will crash when loading the project. This is behavior new to the latest release, 1.9.0.

**To Reproduce**
1. Go to a specific Environment
3. Add a JSON object like `{"pets":" {"cats": "abc"}}` to Data
4. Add a JSON object like `{"pets":" {"dogs": "xyz"}}` to User Data
5. Save and exit
6. Reopen and attempt to reopen the project.

**Expected behavior**
Kreya was previously able to reconcile and merge those objects, and use them properly in templates.

**Environment (if possible, copy the information from the error dialog or the About menu):**
```{
  "kreyaVersion": "1.9.0",
  "platform": "MacIntel",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}```

**Comment by CommonGuy** [comment]
We are able to reproduce this and are working on a bugfix.

**Comment by CommonGuy** [comment]
We released a fix for this on our alpha release channel. To use it, open the "About" window in Kreya and switch to the "Alpha" channel, then check for updates.
