### ISSUE TITLE
Following latest stream response

### ISSUE THREAD

**Issue by anderewrey** [riok/Kreya#125]
**Is your feature request related to a problem? Please describe.**
When observing a gRPC stream, the focus stays on the first response (or the last viewed response).
In fact, a real annoying thing is: the first response is automatically opened while the latest responses are all collapsed. I want to observe the more recent response, not the history.

**Describe the solution you'd like**
Two things:
- Only viewing the last received response (like the "manual" mode with BloomRPC)
- auto-scrolling to the last received response (an improved "interactive" mode, like with BloomRPC)

**Describe alternatives you've considered**
Not with Kreya.

**Comment by CommonGuy** [comment]
Thanks for your suggestion, sounds good! We added it to our backlog

**Comment by CommonGuy** [comment]
With the newly released Kreya 1.12 version, scrolling to the bottom results in following the latest response.
