### ISSUE TITLE
feat: add json path filtering to response view

### ISSUE THREAD

**Issue by buehler** [riok/Kreya#13]
**Is your feature request related to a problem? Please describe.**
A nice feature would be to have the json path filtering possibilities (like insomnia / postman) in the
response view. Since the data is shown in json format, quick searching and mapping of values with json
path could be a nice enhancement.

**Describe the solution you'd like**
Like insomnia; an input field above the json structure where I can insert a valid json path

**Comment by CommonGuy** [comment]
This features just got released in V1.2.0.
