### ISSUE TITLE
Cannot find name ‘kreyaGrpc’ error

### ISSUE THREAD

**Issue by Jagdish2023** [riok/Kreya#132]
**Describe the bug**
I have Kerry’s pro license. I am using Kreya v1.9.0. When I try to use sample code provided on Kreya’s website to add a test for a grpc call, I get error - Cannot find name ‘kreyaGrpc’ error

**To Reproduce**
1. Go to 'Script’ tab on kreya 
2. Copy paste the sample code for a grpc test provided on Kreya’s website (Scripting and tests page)
 Code used - 
kreyagPC. onCallcompleted(call => {
kreya.test( 'Status should be ok', () => expect (call.status .code). to.equal (0));

**Expected behavior**
I would expect Kreya to not throw any errors for using kreyaGrpc object since your website says it is an inbuilt object. But I end up seeing error - Cannot find name ‘kreyaGrpc’ error

**Screenshots
Unable to add screenshots since I am using phone to create this ticket

**Comment by justi7n** [comment]
Thank you for opening this issue.

In what kind of operation are you using the script using `kreyaGrpc` (unary, clientStreaming, serverStreaming, duplex, GET, POST, ...)? 

Could you post the entire script you are using?

Note that you need to use the REST sample if you are working on a REST operation: https://kreya.app/docs/scripting-and-tests/#rest-example

**Comment by Jagdish2023** [comment]
Pls
