### ISSUE TITLE
Can no longer open a project if any directory in the path is not owned by the user

### ISSUE THREAD

**Issue by dsdante** [riok/Kreya#134]
When I try to open a project I created some time ago or to create a new project near the same location, I get an `UnauthorizedAccessException`. [Here](https://pastebin.com/J1wK1JqK) is the full text of the error.

Everything works fine in my home directory, but not when I try to use `/mnt/data/works` or a symlink to it. Trying to browse `/mnt` in Kreya causes the same error.

I suspect it's because `/mnt` belongs to root, and my account has no write permission on it (even though I have read access to it and full rights on `data` and `works` directories).

Everything worked fine in January, when I last used Kreya.

 - OS: Linux Kubuntu 22.04 LTS
 - Kreya Version 1.9.0

**Comment by CommonGuy** [comment]
What exactly are the file's permissions? According to the error message, reading the file fails.

**Comment by dsdante** [comment]
My hypothesis was wrong. I tried creating directories and subdirectories with various owners and permissions and opening them in Kreya.

The error occurs when any directory in the path is not owned by my user, except `/dev`, `/home`, `/lib`, `/proc`, `/sys` and `/tmp`, which are OK. Permissions don't affect Kreya, as long as my user can read the directory.

**Comment by dsdante** [comment]
Via snap.

**Comment by CommonGuy** [comment]
It looks like Kreya is missing the `removable-media` interface, so snap does not allow access to `/mnt`. I'll add this to our backlog
