### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by BartJansseune** [riok/Kreya#136]
**Describe the bug**
Login does not work

**To Reproduce**
On Ubunto 22.04
install kreya through snap
Start Kreya
Goto Preferences
Click login button
Following message appears: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
**Expected behavior**
login popup opens

**Screenshots**
see attachment
![image](https://user-images.githubusercontent.com/6996928/222453582-06815c7f-5b47-4e27-9410-cb9e7334fa42.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: [Ubunt22]
 - Kreya Version [1.10.0-beta.1]

**Comment by CommonGuy** [comment]
We just released 1.10.1, which fixes this issue.
