### ISSUE TITLE
Kreya can get stuck with an "open" connection, stopping subsequent requests

### ISSUE THREAD

**Issue by alteredego** [riok/Kreya#137]
**Describe the bug**
Kreya can get stuck with an "open" connection, stopping subsequent requests.  There appears to be no way to cancel or reset the current operation and you need to close and re-open the Kreya application to perform subsequent requests.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Kreya v1.10.0
2. Make a grpc call that fails, in my case I had a .net exception thrown and Kreya indicated a "1 Cancelled" response
3. Notice the "Sending operation..." spinner
4. Unable to make subsequent requests

**Expected behavior**
Should be able to re-submit a request or to cancel the current/pending request.

**Screenshots**
![image](https://user-images.githubusercontent.com/1997778/223460102-a97889d9-d3ab-4e9c-8d0a-e1a9b2b22c1b.png)
![image](https://user-images.githubusercontent.com/1997778/223460230-dbf1aa28-88fb-412f-a044-053f23518a1c.png)
![image](https://user-images.githubusercontent.com/1997778/223460297-29e21a6b-d387-4a05-8ce3-f6c2f35d7b08.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 10
 - Kreya Version 1.10.0

**Additional context**
N/A

**Comment by CommonGuy** [comment]
Thanks for your bug report. We will look into this.

Are you able to reproduce this bug consistently? If so, could you share the necessary steps?

**Comment by alteredego** [comment]
It is consistently reproducible for me, yes.  I have a local (dev) grpc service and when an exception was thrown from that service, Kreya is showing a "1 Cancelled" response, but doesn't appear to actually end the request?  (From a Kreya perspective, from my service, the connection has responded and has ended).  I have no way to cancel it from the UI.  Presumably this would be similar if I had a really long running query, that it would not be cancellable?  Trace tab is also empty for me.

This has started happening since upgrading to 1.10.0.  Sorry, I can't be certain of what version I had before upgrading.

**Comment by stefanfrings2** [comment]
It happens also always when I enter a wron enumeration value, e.g. `"status": "ACTIVR"` instead of ACTIVE.

**Comment by CommonGuy** [comment]
This has been fixed with the 1.10.1 release.
