### ISSUE TITLE
Unable to start on debian

### ISSUE THREAD

**Issue by TrueGameover** [riok/Kreya#139]
**Describe the bug**
Application can't find a dependencies but they was installed.

**To Reproduce**
1. Run kreya via console

**Expected behavior**
App is starting.

**Screenshots**
Dependencies are missing. Please make sure that 'libgtk-3' and 'libwebkit2gtk-4.0' are installed.

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Linux desktop 6.1.0-5-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.12-1 (2023-02-15) x86_64 GNU/Linux
 - debian bookworm
 - Kreya Version latest available from Kreya-linux.tar.gz

**Additional context**
dpkg -l | grep libgtk-3
ii  libgtk-3-0:amd64                                            3.24.37-2                                                    amd64        GTK graphical user interface library
ii  libgtk-3-bin                                                3.24.37-2                                                    amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common                                             3.24.37-2                                                    all          common files for the GTK graphical user interface library

dpkg -l | grep libwebkit2gtk-4.0
ii  libwebkit2gtk-4.0-37:amd64                                  2.38.5-1                                                     amd64 Web content engine library for GTK

**Comment by CommonGuy** [comment]
We just released Kreya 1.10.1, which should fix this issue
