### ISSUE TITLE
feat: conditional auth settings

### ISSUE THREAD

**Issue by buehler** [riok/Kreya#14]
**Is your feature request related to a problem? Please describe.**
We have the need to make auth settings (per request) conditional. Maybe this could be depending on the environment.
Use case would be: local development does not use any authentication settings because the system under use will fake / mock the authentication, and when the system is deployed (e.g. on a dev environment), OIDC should be used.

**Describe the solution you'd like**
A setting / possibility to set the auth settings per request depending on the environment.

**Comment by CommonGuy** [comment]
This is currently under discussion, as there are many possible solutions to this problem.

**Comment by latonz** [comment]
This can be achieved by using the new feature "project / directory settings" which just got released on the stable channel with version 1.3.0: https://kreya.app/release-notes. Directory and project settings allow to set default settings (auth, metadata, ...) for operations on different levels and specific to environments.

For your use case you could set the OIDC authentication configuration in the project defaults for the dev environment.
