### ISSUE TITLE
Add option to disable evaluation of templates for individual requests

### ISSUE THREAD

**Issue by martinpales** [riok/Kreya#140]
**Is your feature request related to a problem? Please describe.**
I have some requests that contain (go) templated strings and get "The Scriban template contains errors." error in Kreya. These templates should not be evaluated by Kreya, only by the service endpoint.

**Describe the solution you'd like**
It should be possible to disable evaluation of scriban templates in Kreya for some requests.

**Comment by CommonGuy** [comment]
Scriban has a pretty easy option to disable templating: https://github.com/scriban/scriban/blob/master/doc/language.md#13-escape-block. Enclosing your "templated input" with `{%{` and `}%}` should work.

**Comment by ni507** [comment]
Close this issue as a simple and good workaround for this problem is available.
