### ISSUE TITLE
Add ability to execute script before the request

### ISSUE THREAD

**Issue by CosminGramada** [riok/Kreya#141]
**Is your feature request related to a problem? Please describe.**
Sometimes is useful to be able to execute a script before the request is performed.
For example, in the case of tests, it would be useful to be able to create variables with dynamic data (faker / bogus) that will be used in the request and afterward for assertions in the tests.

**Describe the solution you'd like**
I see 2 possible options: 
1.  Before Script tab -> everything inside will be executed before the request
2. Use the same Script tab and have available `onRequest` / `beforeRequest` events that get executed before the request is performed

**Comment by CommonGuy** [comment]
This is already supported. I used the "addsvc.Add.Sum" operation from the examle project:

```
import { expect } from 'chai';

// These variables are set before the call starts
kreya.variables.set('var1', 2);
kreya.variables.set('var2', 3);

kreyaGrpc.onResponse(response => {
  kreya.test('sum', () => expect(response.content.v).to.equal("5"))
})
```

In the request, I referenced the [user variables](https://kreya.app/docs/templating/#referencing-user-variables-) like this:
```
{
  "a": "{{ vars.var1 }}",
  "b": "{{ vars.var2 }}"
}
```

![grafik](https://user-images.githubusercontent.com/8035999/227458628-c949a4d4-2c65-4d4e-92b7-559ad7210e81.png)

**Comment by CosminGramada** [comment]
@CommonGuy 
Oh, I see. Thank you for the update. Seems like the use case is resolved.

**Comment by CosminGramada** [comment]
Tried to test this approach but from what I'm seeing `kreya.variable.set` works only with static data.

E.g. 
`kreya.variables.set("var1", "{{ faker.internet.example_email }}");`

Am I missing something?
