### ISSUE TITLE
[MacOs] New version doesn't get installed

### ISSUE THREAD

**Issue by CosminGramada** [riok/Kreya#142]
**Describe the bug**
New Kreya version doesn't get installed.

**To Reproduce**
1. Open the application
2. Click on Kreya -> About
3. Click Check for updated
4. Wait for download of the new version
5. Click Relaunch
6. Check new version

**Expected behavior**
New version available installed.

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - Apple M1 Pro
 - OS: MacOS 13.2.1
 - Kreya Version 1.10.0 -> 1.10.1
 

![gif Mar-23-2023 23-32-12](https://user-images.githubusercontent.com/15174660/227368819-67dd8ffc-2c16-4e6a-ba1e-99d675a5cf15.gif)

**Comment by CommonGuy** [comment]
Does this problem still exist? I saw in https://github.com/riok/Kreya/issues/144 that you are now updated to the 1.10.1 version.

At the time of updating, did you have multiple Kreya instances open?

**Comment by CosminGramada** [comment]
@CommonGuy 
I mistakenly tagged the version as 1.10.1 (updated #144 to reflect the correct version).
I wasn't able to upgrade to 1.10.1, I see it as ready but at relaunch I'm still on the old version.


![Screenshot 2023-03-24 at 11 14 48](https://user-images.githubusercontent.com/15174660/227476478-1f136be0-1060-4b93-8ac8-ddff7a42135b.png)

**Comment by CosminGramada** [comment]
If it's not helpful, could you share the previous version, 1.10.0, so that I can try to reproduce it again?

**Comment by CosminGramada** [comment]
Glad to hear you found the underlying issue.
