### ISSUE TITLE
[macOS] shortcut "command + h" is taken

### ISSUE THREAD

**Issue by Hawken94** [riok/Kreya#145]
**Describe the bug**
The default macOS shortcut key "command+h" is already taken by history for operations in v1.10.0

**To Reproduce**
1. command +h
2. show the history, but i want hide the app
<img width="386" alt="image" src="https://user-images.githubusercontent.com/12959892/227562523-ef7c8b82-3e41-498b-b41c-e0c7717ad8dd.png">

**Expected behavior**

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: [e.g. macOS 13.2.1]
 - Kreya Version [e.g. 1.10.1]

**Comment by CommonGuy** [comment]
Thanks for reporting this, we will change the shortcut in the next version.

**Comment by CommonGuy** [comment]
With the newly released 1.11 version, the shortcut has been changed to "command + shift + h"
