### ISSUE TITLE
[gRPC] Ability to run all requests in a folder

### ISSUE THREAD

**Issue by CosminGramada** [riok/Kreya#146]
**Is your feature request related to a problem? Please describe.**
When writing tests for an API, usually, multiple requests are necessary (e.g. Searching for a user has a prerequisite the user creation).

**Describe the solution you'd like**
Ability to run all requests in a folder.
Either a Run button when the folder is selected or at right-click.

**Comment by CommonGuy** [comment]
This goes in a similar direction as https://github.com/riok/Kreya/issues/107.

We want to create a view where one can configure and run the tests

**Comment by CommonGuy** [comment]
[Collections](https://kreya.app/docs/collections/) have been added to Kreya with the just released 1.13 version

**Comment by CommonGuy** [comment]
The upcoming 1.14 release contains support for running all operations inside a folder
