### ISSUE TITLE
Add metadata to requests

### ISSUE THREAD

**Issue by MarcinGinszt** [riok/Kreya#149]
I can't use your client because it's missing most basic authentication option.

I would like to manually add {"Authentication": "Bearer XYZ1234"} to my requests, as existing options to get the token are not allowing me to retrieve the token. 

Option to add metadata exists in all grpc clients.

**Comment by CommonGuy** [comment]
With the newest version of Kreya, static authentication values are supported:
![grafik](https://user-images.githubusercontent.com/8035999/233286864-3408893c-db23-4c38-a796-11c356c4e914.png)

It is also possible to add it via metadata:
![grafik](https://user-images.githubusercontent.com/8035999/233287581-a3e78096-e3f4-46e6-bae2-7666300710a1.png)

Does this solve your problem?

**Comment by CommonGuy** [comment]
Closing this as no further information was provided.
