### ISSUE TITLE
CTRL + Enter command no longer sending

### ISSUE THREAD

**Issue by agentgoomba** [riok/Kreya#151]
**Is your feature request related to a problem? Please describe.**
In the previous build, a user was able to use the keyboard shortcut "ctrl + enter" to send a request. this is no longer working.

**Describe the solution you'd like**
can we have ctrl + enter act as the green send button

**Describe alternatives you've considered**
A different shortcut combination to send a request.

**Additional context**
When ctrl + enter is pressed, you see the message on the bottom left corner with the message "Operation Sent", however nothing happens.

**Comment by CommonGuy** [comment]
I cannot reproduce this bug locally, CTRL + Enter works for me.

Could you provide more information? Which Kreya version are you using on which operation system? Does this happen with all operations, all the time or do some of them work?

**Comment by Hawken94** [comment]
I meet same bug. Sometimes it works, sometimes it doesn't work. And other shortcuts have the same problem. If restart the app, it will work agin, but the history will disappear.

version info : 
{
  "kreyaVersion": "1.10.1",
  "releaseChannel": "stable",
  "osDescription": "Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64",
  "osVersion": "Unix 13.3.1",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "osx.13-x64",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}

**Comment by CommonGuy** [comment]
I was able to reproduce this bug. It happens when you open multiple operations, meaning several tabs are open.

Switching to another tab doesn't update the shortcut binding. Hitting CTRL + Enter sends the operation that was previously selected and not the one that is currently open. We will fix this in the next release.

**Comment by CommonGuy** [comment]
Kreya 1.11 was just released, which fixes this issue
