### ISSUE TITLE
Importing proto files on a different drive doesn't work correctly

### ISSUE THREAD

**Issue by hernandgr** [riok/Kreya#156]
**Describe the bug**
I am using Kreya in Windows 11 machine with 2 hard drives (C: and D:). If I create a Kreya project on C: drive and try to import proto files on D: drive the path generated by Kreya seems that is not working.

**To Reproduce**
1. Create a project and store it in a folder on C: drive
2. Click on 'gRPC' on Initial project setup screen and 'Next'
3. Select 'Proto files' and then 'Add proto directory'.
4. Select a folder with some proto files that should be stored in D: drive. (Note the '..\\..\\..\\' characters in the path before the D: drive)
5. See that no operations are imported in the main screen
6. If I edit the proto files path to remove the  '..\\..\\..\\' characters in the path before the D: drive then I can see the operations imported.

**Expected behavior**
Selecting a folder with some proto files in a different drive should generate the right path to import the operations.

**Screenshots**
![image](https://github.com/riok/Kreya/assets/2015653/442b5307-d922-436e-99d8-96e7aebd1a15)

![image](https://github.com/riok/Kreya/assets/2015653/44080cc4-eb04-4f94-b890-f082b18769cd)

![image](https://github.com/riok/Kreya/assets/2015653/7ed509b9-b7d7-49e3-a824-dab23e541d03)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 11
 - Kreya Version 1.10.1

**Additional context**
I was able to see the same behavior with certificate paths.

**Comment by CommonGuy** [comment]
Kreya tries to store references to other files as relative paths (to the project location), which has advantages when the project is being shared with other persons.

With different drives on Windows, this is not possible, but Kreya tries to create a relative path anyway. We should fix this and just store an absolute path in this case

**Comment by CommonGuy** [comment]
With the newly released 1.11 version, this is now supported
