### ISSUE TITLE
Mac OS - Kreya crashes immediately upon open

### ISSUE THREAD

**Issue by mikewagnercmp** [riok/Kreya#165]
**Describe the bug**
Downloaded mac OS X64. Unzipped and attempted to open the app. Immediately crashed

**To Reproduce**
Downloaded mac OS X64. Unzipped and attempted to open the app. Immediately crashed

**Expected behavior**
App to open

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Ventura 13.5
 - Kreya Version v 1.11 per download page.

**Additional context**
stack trace

Failed to initialize Kreya: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3.dylib, 0x0001): tried: '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3.dylib' (no such file), '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3.dylib' (no such file)
dlopen(e_sqlite3.dylib, 0x0001): tried: 'e_sqlite3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSe_sqlite3.dylib' (no such file), '/usr/lib/e_sqlite3.dylib' (no such file, not in dyld cache), 'e_sqlite3.dylib' (no such file), '/usr/lib/e_sqlite3.dylib' (no such file, not in dyld cache)
dlopen(/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3.dylib, 0x0001): tried: '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3.dylib' (no such file), '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3.dylib' (no such file)
dlopen(libe_sqlite3.dylib, 0x0001): tried: 'libe_sqlite3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibe_sqlite3.dylib' (no such file), '/usr/lib/libe_sqlite3.dylib' (no such file, not in dyld cache), 'libe_sqlite3.dylib' (no such file), '/usr/lib/libe_sqlite3.dylib' (no such file, not in dyld cache)
dlopen(/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3, 0x0001): tried: '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3' (no such file), '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/e_sqlite3' (no such file)
dlopen(e_sqlite3, 0x0001): tried: 'e_sqlite3' (no such file), '/System/Volumes/Preboot/Cryptexes/OSe_sqlite3' (no such file), '/usr/lib/e_sqlite3' (no such file, not in dyld cache), 'e_sqlite3' (no such file), '/usr/lib/e_sqlite3' (no such file, not in dyld cache)
dlopen(/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3, 0x0001): tried: '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3' (no such file), '/private/var/folders/dh/b1mvrx712bs_yxnw6_mbd2jh0000gn/T/AppTranslocation/066C2027-DE24-4B56-B8B0-032C32A06B30/d/Kreya.app/Contents/MacOS/libe_sqlite3' (no such file)
dlopen(libe_sqlite3, 0x0001): tried: 'libe_sqlite3' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibe_sqlite3' (no such file), '/usr/lib/libe_sqlite3' (no such file, not in dyld cache), 'libe_sqlite3' (no such file), '/usr/lib/libe_sqlite3' (no such file, not in dyld cache)

at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
at SQLitePCL.Batteries_V2.Init()
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters

![image](https://github.com/riok/Kreya/assets/23058476/160c7ed0-efa0-463f-995f-74ce6d71a6b1)

**Comment by zhengmou** [comment]
same problem for me

**Comment by CommonGuy** [comment]
@zhengmou Are you also on Mac OS X64?

**Comment by CommonGuy** [comment]
We are able to reproduce this error on Mac OS x64. ARM64 is not affected.

**Comment by zhengmou** [comment]
@CommonGuy nop, M1 Pro chip. ARM64

**Comment by CommonGuy** [comment]
Thanks for the information. It looks like both x64 and ARM64 are affected from the bug, but only new installations (not updates from previous versions).

We are working on a fix

**Comment by CommonGuy** [comment]
@zhengmou @mikewagnercmp As a workaround, you can download an older version at https://stable-downloads.kreya.app/Kreya-macos-x64.zip (for x64) or https://stable-downloads.kreya.app/Kreya-macos-arm64.zip (for ARM64)

**Comment by CommonGuy** [comment]
We just released the 1.11.1 bugfix release, which fixes this issue.

If you encountered this problem, please download Kreya again from https://kreya.app/downloads/.
