### ISSUE TITLE
Using an importer with a prefix directory but no project subdirectory fails

### ISSUE THREAD

**Issue by timw** [riok/Kreya#166]
**Describe the bug**
When a prefix directory to trim is defined for an importer, but a project subdirectory is not, then importation fails with an error: _System.InvalidOperationException: cannot create operations outside the project directory_.

**To Reproduce**
1. Define an importer (in my case a gRPC server reflection importer)
2. Define a prefix directory to trim (in my case `project/grpc`)
3. Save the importer (which runs it often, otherwise run importers)

**Expected behavior**
The importer should run and import each of the services into the top level of the project (in my case, there are always additional directory paths under `project/grpc`, so the top level of the project should be a group of directories.

**Screenshots**
![image](https://github.com/riok/Kreya/assets/670828/33a83521-a09d-416a-88a5-5cd05dda6a4c)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Mac/Arm64
 - Kreya Version 1.11.1

**Additional context**
Adding a project subdirectory works as expected - services are imported under that root, with the prefix parts of the service path trimmed.

**Comment by CommonGuy** [comment]
Thanks for the detailed bug report, we'll fix this issue.

As a workaround, you can enter `.` as the project subdirectory, which will create the operations in the root directory as expected.

**Comment by CommonGuy** [comment]
This should be fixed with the newly released 1.12 version.
