### ISSUE TITLE
Does this support ANY protobuf type

### ISSUE THREAD

**Issue by banandh** [riok/Kreya#167]
Hi - I have a proto defined with ANY as type

message Request{
google.protobuf.Any request = 1;
}

message Response{
google.protobuf.Any response = 1;
}

How does this tool helps with customizing this ANY object in request? I see some limitations with other gRPC client tools, wombat supports any object?

**Comment by CommonGuy** [comment]
Kreya supports the Any type out of the box. For example in a request:

```
"myAnyField": {
  "@type": "type.googleapis.com/google.protobuf.StringValue",
  "value": "fooBar"
}
```
