### ISSUE TITLE
Allow to override the shortcuts to keep Monaco support

### ISSUE THREAD

**Issue by ppcamp** [riok/Kreya#169]
**Is your feature request related to a problem? Please describe.**
No.
Seems that kreya uses Monaco as a base editor, therefore, we have all features that Monaco supports such as format, search, fold, etc. Although, the Kreya client overrides the shortcuts for that (ctrl+p and F1)

**Describe the solution you'd like**
It'll be nicer if we have a page to disable those keybindings to print/help support, allowing then, to use the Monaco editor completely.

**Describe alternatives you've considered**
I think it'll be a nice change, since the cacheForReqAndRes + MonacoEditor is the reason why I've chosen to use Kreya, when compared to others programs such as grpcui.

**Additional context**
Notice that I'm still able to use it by hitting `ctrl+shift+o` and then, deleting the string, OR by clicking with right button mouse, to open the Command palette (notice, however, that it shows that we have support to hit `F1`)

![image](https://github.com/riok/Kreya/assets/38117637/591cf056-a49e-4f4d-ba90-5da0b9acf14b)

**Comment by CommonGuy** [comment]
A fix for this has been implemented and was released with the newest beta release. It will be included in the next stable version.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released, which fixes this
