### ISSUE TITLE
[Display] Change response font

### ISSUE THREAD

**Issue by haunt98** [riok/Kreya#171]
**Is your feature request related to a problem? Please describe.**
I want to change default font in response view.

**Describe the solution you'd like**
Another setting to change font

**Additional context**
Insomnia allows to change both display, editor font easily.

**Comment by hoyau** [comment]
It sounds unusual to make the font configurable, may I ask why you need this? Is there a particular reason?

**Comment by haunt98** [comment]
@hoyau Want to change font/edit font size to match my preferences (Bad eyes)
Of course it's not must have features.
But both Postman, Insomnia has that features and I see blog comparision Kreya about those two so I want to make suggestion.

**Comment by CommonGuy** [comment]
We enabled the font zoom in the editor with Kreya v1.12

**Comment by haunt98** [comment]
Thank you @CommonGuy
