### ISSUE TITLE
Sharing Kreya files using Sharepoint/OneDrive causes environment files to get deleted

### ISSUE THREAD

**Issue by vyruz1986** [riok/Kreya#174]
**Describe the bug**
We're using Kreya in a team of 4 developers, to share projects and gRPC calls for the various environments we work on.
We're trying to accomplish this by using MS Sharepoint's document library feature, and Microsoft OneDrive on our development machines. The OneDrive app will take case of synching any file changes across the users machines.

What happens frequently when multiple poeple are editing the same Kreya project, is that at some point, a kreya environment file (`*.krenv`) will be deleted by one of the users, obviously this was not done manually or intentionally, so we assume Kreya is doing something 'weird' which causes this deletion to happen. I also doubt this is caused by colliding edit operations, as OneDrive normally will alert users in case 1 file is edited in 2 locations, and will create 2 new files, with the editor's machine name as a prefix.

I don't have reliable steps to reproduce, it happens at random times, but also when we try to reproduce it by editing the same project with multiple users, it's mostly not reproducable.

**To Reproduce**
Unclear...

**Expected behavior**
Environment files should remain in place.

**Screenshots**
N/A

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 11
 - Kreya Version: 1.11.1

**Comment by CommonGuy** [comment]
Thanks for your bug report. We'll try to reproduce and fix this.

I suspect OneDrive may delete the `*.krenv` file and then create a new one (with the changed data). Kreya receives the "file deleted event" and does not recognize that a new file with the same data has been created in the meantime.

**Comment by CommonGuy** [comment]
This should be fixed with the newly released 1.12 version.
