### ISSUE TITLE
localhost:9000 or 127.0.0.1:9000 does not accept as a valid URL

### ISSUE THREAD

**Issue by baxsmaxbax** [riok/Kreya#175]
**Describe the bug**
It is not possible to create a project for local testing

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 10
 - Kreya Version 1.11.1 (2023-08-23)

**Comment by CommonGuy** [comment]
Kreya expects an URL with a scheme.

Try `http://localhost:9000`
