### ISSUE TITLE
Environment variables in import paths

### ISSUE THREAD

**Issue by CommonGuy** [riok/Kreya#18]
Some users store their external protobuf files in a central folder, ex. `$GOPATH/src` for Go programmers.

Currently, only relative import paths are supported. We will add a method to add import paths with environment variables, so that such Kreya projects can be shared between users.

**Comment by CommonGuy** [comment]
Feature is included in the v1.6 release

**Comment by andreassiegel** [comment]
Hi @CommonGuy,

should this work with any environment variable?

I'm currently experiencing an issue with environment variables in the import path: It works fine if I use `$HOME` but I actually want to use a "custom" environment variable that refers to a specific workspace directory. Therefore, I set an environment variable like `MY_SERVICES_ROOT` in my `.zshrc` or `.zprofile` files but Kreya is not able to resolve these variables.

Instead, the string `${MY_SERVICES_ROOT}` gets appended to the project location, basically turning into an attempt to import from a relative path.

**Comment by CommonGuy** [comment]
@andreassiegel Yes, any environment variable is supported. Your example should work, I just tried it myself...

Kreya probably does not have access to the environment variables you set. Could you verify this by calling `env` in the command line before launching Kreya from the same command line interface?
