### ISSUE TITLE
Enhance reporting for automated runs

### ISSUE THREAD

**Issue by scheroiu** [riok/Kreya#181]
We are running Kreya tests directly in Azure via pipelines. Would be pretty awesome to have kreya export some reports from the test results in a standard format. Similar with how newman (Postman) does it with their reporting.  

For our use case a junit report XML file is enough.

**Comment by CommonGuy** [comment]
Good idea, I'll add this to our roadmap.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released, which includes the JUnit report feature, see https://kreya.app/docs/cli/commands/operation/invoke/#test-report-junit
