### ISSUE TITLE
Using template in Authentications doesn't use updated value

### ISSUE THREAD

**Issue by mitchellsullivan** [riok/Kreya#186]
When using a templated value in an Authentication, if the value of the variable is updated, it isn't reflected in the Authentication. For example, if one sets the value to `{{ vars.bearer_token }}`, only the current value of this variable is used in the Authentication. 

Every time the value of that variable is updated, one must return to this screen and hit "Save" again to reset the value.  It should be updated dynamically in the background, i.e., every time an `onResponse` script sets the value to something else.

![Screenshot 2023-12-11 at 9 49 51 AM](https://github.com/riok/Kreya/assets/15097321/1709c93c-fbe5-49a9-820a-875916743398)

**Comment by CommonGuy** [comment]
Thanks for the bug report, this is indeed annoying. We will fix this in the next release.

**Comment by CommonGuy** [comment]
This is fixed with the newly released 1.13 version
