### ISSUE TITLE
feat: support OAuth2 client credentials and password grants

### ISSUE THREAD

**Issue by pfyod** [riok/Kreya#19]
**Is your feature request related to a problem? Please describe.**
It looks like right now Kreya only supports the Authorization Code grant

**Describe the solution you'd like**
Client Credentials and Password grants should also be supported

**Comment by CommonGuy** [comment]
We released this feature on our Beta-channel: https://kreya.app/release-notes/beta. You can switch to the Beta release channel in the app via Kreya -> About. Change the release channel to Beta and search for updates. It should then install the newest Beta version. Please note that the Beta channel may contain some unstable features.

We expect to release this feature in the stable version of Kreya in the next 1-2 weeks.

**Comment by latonz** [comment]
This feature is released on the stable channel with version 1.3.0: https://kreya.app/release-notes.
