### ISSUE TITLE
Right UI Pane Doesn't Size Properly

### ISSUE THREAD

**Issue by bitm0de** [riok/Kreya#193]
The right window pane no longer sizes properly...

**To Reproduce**
Try resizing the right pane.

**Expected behavior**
Resizing as normal.

**Screenshots**
![image](https://github.com/riok/Kreya/assets/14263968/37795190-5f62-4b2f-b741-0dbeb7e5b22f)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 11
 - Kreya Version: 1.13.0 (2024-01-29)

**Additional context**
I just updated recently and this is an extremely annoying problem that interrupts productivity.

**Comment by CommonGuy** [comment]
Thanks for your bug report. Are you hitting this problem consistently?

We are able to reproduce it sometimes, but not always

**Comment by bitm0de** [comment]
On my machine it always happens, I haven't seen it work properly once when moving my mouse left to right while dragging. It's pretty unusable at this point.

**Comment by jakobmollas** [comment]
Same thing here, have tested it out on 2 different machines.
I updated from 1.8 if that is of any help.

**Comment by CommonGuy** [comment]
This should be fixed with Kreya 1.13.1, which has been released just now
