### ISSUE TITLE
Custom Content-type not formatted correctly

### ISSUE THREAD

**Issue by marudor** [riok/Kreya#197]
**Describe the bug**
Currently kreya does not format responses if they use a custom content-type (with a suffix based on RFC 6839)

**To Reproduce**
Get a response that has a custom content-type with a +json suffix to inidcate structure

**Expected behavior**
Kreya should format ist based on the suffix

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: macOS 14.3.1
 - Kreya Version 1.13.0

**Additional context**
My exact example is a response that has "application/vnd.de.db.ris+json" as "Content-Type" Header.
The +json indicates that it is a json and should be formatted like one. The same response with a "application/json" header is formatted correctly.

**Comment by CommonGuy** [comment]
A fix for this has been implemented and was released with the newest beta release. It will be included in the next stable version.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released
