### ISSUE TITLE
An unexpected error occured: Unknown API call "TelemetryUiService.isEnabled"

### ISSUE THREAD

**Issue by genc-murat** [riok/Kreya#199]
{
  "kreyaVersion": "1.13.1",
  "releaseChannel": "stable",
  "osDescription": "Microsoft Windows 10.0.22621",
  "osVersion": "Microsoft Windows NT 10.0.22621.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
}

null

**Comment by CommonGuy** [comment]
What are the steps to reproduce this?

**Comment by genc-murat** [comment]
When I press settings under Kreya in the menu

**Comment by CommonGuy** [comment]
This happens every time you go to the settings? Very weird, since I cannot reproduce this...

**Comment by CommonGuy** [comment]
Closing this as no further feedback was provided and since I cannot reproduce this.

If the issue persists, try re-installing Kreya.
