### ISSUE TITLE
Untrusted SSL

### ISSUE THREAD

**Issue by NuSkooler** [riok/Kreya#20]
The ability to allow untrusted SSL (self signed, or unexpected CNs, so on) would be great!

**Comment by CommonGuy** [comment]
Great idea! Will definitely implement this soon.

**Comment by CommonGuy** [comment]
We released this feature on our Beta-channel: https://kreya.app/release-notes/beta. You can switch to the Beta release channel in the app via Kreya -> About. Change the release channel to Beta and search for updates. It should then install the newest Beta version. Please note that the Beta channel may contain some unstable features.

We expect to release this feature in the stable version of Kreya in the next 1-2 weeks.

**Comment by NuSkooler** [comment]
Thank you for this!

**Comment by latonz** [comment]
This feature is released on the stable channel with version 1.3.0: https://kreya.app/release-notes.
