### ISSUE TITLE
Running multiple collections using one CLI command

### ISSUE THREAD

**Issue by mfridrikhson** [riok/Kreya#200]
**Is your feature request related to a problem? Please describe.**
We want to use Kreya for running integration tests on our APIs. Each collection is regarded as a single integration test and there may be multiple of them to cover all the possible cases. As you may imagine with an ever-growing functionality it would become hard to maintain a list of all the operations to run, especially if we are to run the tests as a step in our CI pipeline.

**Describe the solution you'd like**
It would be great to have an option to run all the collections under a single project and/or to have an ability to specify a path with a pattern to cover multiple collections at once (like it works for `kreyac operations invoke`).

**Comment by CommonGuy** [comment]
Thanks for your feature request. We plan to implement this with the next release

**Comment by CommonGuy** [comment]
This has been implemented and was released with the newest beta release. It will be included in the next stable version.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released, which allows to invoke multiple collections in one command
