### ISSUE TITLE
Kreya Window doesn't have title

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#208]
Here's probably the smallest bug (is it really a bug ?) ever reported :) 

When Kreya is launched from Start menu, window does not have title.
![image](https://github.com/riok/Kreya/assets/23377911/fa5a2c87-d877-4205-add9-13bf6077fbcd)

Title only appears when a project is loaded: 
![image](https://github.com/riok/Kreya/assets/23377911/63fbcbaf-ea09-46aa-b0b0-a1d7abb4b1da)

Same in Windows taskbar of course:
![image](https://github.com/riok/Kreya/assets/23377911/909a619f-8c88-4327-950e-a4466ad060eb)

(seen in 1.14 beta, probably also there in previous versions)

**Comment by CommonGuy** [comment]
Thanks for your bug report, we'll fix this in the next stable release.

**Comment by CommonGuy** [comment]
A fix for this has been implemented and was released with the newest beta release. It will be included in the next stable version.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released
