### ISSUE TITLE
Bad handling of query/collection rename

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#209]
**Describe the bug**
Kreya allows to rename a collection, a request or a folder with a name not supported by file system.
Kreya displays an error, but it should also corrupt something internally, because **after it's not possible to rename the query. Kreya must be closed and reopened**.
This case seems to be handled properly when creating a new request, but not for rename : 
![image](https://github.com/riok/Kreya/assets/23377911/18237465-e038-44e6-a6ec-2dcea8b21ab4)

In 1.14 beta, but probably also previous versions. 

**To Reproduce**
Create a query
Rename it, for example with a "*" in its name

**Comment by ni507** [comment]
Thank you for your report. We will fix this in the next release.

**Comment by CommonGuy** [comment]
A fix for this has been implemented and was released with the newest beta release. It will be included in the next stable version.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released
