### ISSUE TITLE
Unable to locate source for the repo

### ISSUE THREAD

**Issue by gravypod** [riok/Kreya#21]
**Is your feature request related to a problem? Please describe.**
I was unable to find the source code in the github repo and I couldn't find any links on your website (https://kreya.app/).

**Describe the solution you'd like**
If possible, a link to where I could download the source code.

**Describe alternatives you've considered**
N/A

**Additional context**
This project looks much better than BloomRPC (something I currently use) and I want to use it at home. I usually try to build the software I use from source.

**Comment by CommonGuy** [comment]
Kreya is not open source at the moment, though this may change in the future.

Our main reason is that we fear that others may "steal" Kreya, ex. the same thing that happened to ElasticSearch: https://www.elastic.co/blog/why-license-change-AWS. I suspect this is the reason why the main parts of Postman or https://paw.cloud/ aren't open source as well. Things could get especially tricky if we decide to monetize parts of Kreya.

The decision is not set in stone, as we see the benefits of open sourcing Kreya.
