### ISSUE TITLE
"Add operation" popup in Collection does not open sometimes

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#210]
In 1.14 beta, In several occasions the button "Add operation" in collection was unresponsive : popup doesn't open, background doesn't go dim, no error displayed... Only the "style" for the button click event occurs, but nothing else.

Here's an animated GIF : 
![test](https://github.com/riok/Kreya/assets/23377911/3db46e56-815c-4a11-8336-029dd6dcd653)

I have tried to find the exact way to reproduce it but I didn't found : toggling between various elements in the project, reducing/restoring kreya windows, switching to other apps, wait, try another project... I didn't find a consistent root cause (Windows 10 last version, all other Kreya UI features working properly so probably something related directly to this button).

Closing and reopening Kreya and the project seems to fix (temporarily) the problem.

**Comment by ni507** [comment]
Again, thank you for your report. I was also able to reproduce it, we will have a fix for this in the next version.

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released, which fixes this
