### ISSUE TITLE
Prevent empty headers or make them more obvious, especially when they come from inherited entry

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#213]
In Environment -> Headers, it's possible to define and save completely empty headers :
![image](https://github.com/riok/Kreya/assets/23377911/2640d964-a4c4-425f-8267-72eaf0704c71)

Later, when executing a request there's a warning regarding the empty header, and only a thin gray line to show it (as it's inherited and not editable, it's almost invisible) : 
![image](https://github.com/riok/Kreya/assets/23377911/51a35281-2f55-4f97-a13e-ba91db1d95de)

It would be interesting to make the empty header more visible (I had to search were it was to understand the warning) and/or to warn when saving an empty header in environment settings.

**Comment by CommonGuy** [comment]
Thanks for reporting this bug, we'll fix this in the next release

**Comment by CommonGuy** [comment]
Kreya 1.14 has been released, which fixes this
