### ISSUE TITLE
Expand / collapse JSON in call results panel

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#214]
Hello, 
Some of my methods returns very long JSON (1MB or more), with deep nesting. Current braces coloring feature is nice, but not enough unfortunately.
![image](https://github.com/riok/Kreya/assets/23377911/2c7cb394-49d3-4edf-8ec2-74b116ae98f9)

It's very difficult to browse the results with current way to display them.

A feature to be able to collapse/expand individual JSON elements  and tables (like in any good text processor) would be greatly appreciated for a future release :)

Thank you !

**Comment by CommonGuy** [comment]
This should already work by hovering over the column next to the line number:
![grafik](https://github.com/riok/Kreya/assets/8035999/2ad984e0-c28d-4682-9053-26b3bcd186bc)

Clicking these arrows collapses the JSON elements

**Comment by AFract** [comment]
Sorry, I missed that when I was looking for it ! Thank you (a bit in late) for the answer.
