### ISSUE TITLE
Ability to send Client TLS Certificate

### ISSUE THREAD

**Issue by NuSkooler** [riok/Kreya#22]
The ability to provide a client TLS certificate would be great! I have a number of services I'd like to use Kreya with that require client TLS authentication.

Note that generally this can be used in _addition_ to the existing authentication types. It would require a field for a certificate and key or a single field for a both (probably depending on what your underlying library actually wants).

**Comment by CommonGuy** [comment]
Yes, this is definitely something that Kreya needs to support. We'll implement this soon :)
