### ISSUE TITLE
Ability to see the full path of Kreya project and related files 

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#221]
Hello, 

Here's an improvement proposal :
I have the "same" Kreya project on several folders of my drive, due to Git branching, as Kreya is located near sources. This is oftenly confusing when several Kreya are opened.

In Kreya UI, there's no obvious way to see the path of the currently opened project, or to navigate to its location. 
I have just noticed the "Open in Explorer" option when click on an operation in left menu (which is not the first place where you search it I think).

it would be nice to have also : 
- Full project path visible (and copyable) somewhere
![image](https://github.com/riok/Kreya/assets/23377911/e9ac6483-e14a-4f84-940f-0e417f5c180e)
- Features like right-clicking on an operation tab and Navigate to folder option
![image](https://github.com/riok/Kreya/assets/23377911/3e9f2d35-a14b-4edc-abe6-4da6a67e0e11)

Regards

**Comment by ni507** [comment]
Hi and thanks for your porposal. We will definitely improve it.

**Comment by CommonGuy** [comment]
This has been fixed in the latest beta version and will be released in the next stable version

**Comment by CommonGuy** [comment]
Kreya 1.15 has just been released, which added the ability to show paths for Kreya files.
