### ISSUE TITLE
Option to automatically create new methods calls when loading updated contract

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#223]
Hello, 

When clicking on the refresh button of an Importer (in REST for example)
![image](https://github.com/riok/Kreya/assets/23377911/55080869-85a0-4e9e-9cdd-bc18250ad4f6)

It would be nice to have an option to automatically generate sample calls for all new discovered methods in updated Swagger, instead of having to search them from the "Add > New operation > Use imported API definition as template" panel.

Maybe a such option already exists, but I wasn't able to find it.

Thank you.

**Comment by CommonGuy** [comment]
This feature already exists: https://kreya.app/docs/importers/#generating-operations-automatically

Simply check the "Create an operation for each API method" checkbox in your OpenAPI importer

**Comment by CommonGuy** [comment]
Good idea, I have added this to our backlog
