### ISSUE TITLE
API operations have empty URLs after import from Postman or Insomnia

### ISSUE THREAD

**Issue by andreassiegel** [riok/Kreya#225]
**Describe the bug**

Whenever I import a project from an existing Postman collection or Insomnia collection, the general structure or hierarchy of requests and folders is imported as expected.

However, the request path is empty for all operations which results in a pointless import.

**To Reproduce**

1. Go to 'Import…'
2. Select the existing collection to import
3. Confirm the import
4. Open any of the operations in the new Kreya project
5. Check the request path

**Expected behavior**

The request path should be taken over from the imported collection.

Ideally, the host should be imported as endpoint in the settings, and the rest of the URL should be the request path.

**Screenshots**

_None._

**Environment:**
 - OS: MacOS Sonoma 14.4.1
 - Kreya Version 1.14

**Additional context**

The issue occurs regardless of whether I try to import Insomnia or Postman collections of the same original project.

I can only get the desired result if I basically start from scratch and configure OpenAPI importers.

**Comment by CommonGuy** [comment]
After importing, is the full request path added to the endpoint (open a Kreya operation, click the Settings tab, check the Endpoint field)?

If so, Kreya may not recognize the "format" (e.g. due to templating) and is not able to separate the host from the rest of the request path

Could you add an example of your path format?

**Comment by andreassiegel** [comment]
> After importing, is the full request path added to the endpoint (open a Kreya operation, click the Settings tab, check the Endpoint field)?

No, it is completely empty:

<img width="1512" alt="image" src="https://github.com/riok/Kreya/assets/13197892/27fcebbd-2a8c-47f5-91a9-f685f824e1d7">

<img width="1512" alt="image" src="https://github.com/riok/Kreya/assets/13197892/f92bf284-d063-49e3-9e28-ff2649c02f76">

<img width="1512" alt="image" src="https://github.com/riok/Kreya/assets/13197892/9d2c5c05-e24e-4af5-ab13-6dfcae9a373c">

> If so, Kreya may not recognize the "format" (e.g. due to templating) and is not able to separate the host from the rest of the request path
>
> Could you add an example of your path format?

This is a good hint! Thank you!

I found one directory where at least the paths of the operations were set (but also no host in the endpoint settings).
In this case, the URL in the collection was something like `https://example.com/foo/bar/:param`.

All other URLs look like this: `{{base-url}}/foo/bar/:param`, using an environment variable for the schema and host.

**Comment by CommonGuy** [comment]
Can you also show the Settings of the operation itself? I think an endpoint is set, as the "Send" button is enabled:

For example:
![grafik](https://github.com/riok/Kreya/assets/8035999/4c381107-2fc3-48d8-96ed-cde7b1dec484)

**Comment by andreassiegel** [comment]
Aha! You're right, there it is:

<img width="1512" alt="image" src="https://github.com/riok/Kreya/assets/13197892/727e2a5e-3ba1-4cde-9844-10f395908f04">

Is this the expected behavior or could the import be changed to only use the variable as the endpoint?

Also, the variable reference is not "detected" as an environment variable. Would it be possible or make sense to import `{{my_var}}` as `{{env.my_var}}`?

**Comment by CommonGuy** [comment]
Kreya currently recognizes templates paths such as `{{scheme}}://{{host}}/path`. It probably makes sense to also support `{{base-url}}/path` like in your example.

I'll see whether automatic conversion from `{{base-url}}` to `{{ env.base_url }}` should also be implemented, as hyphens are never valid in templates in Kreya.

**Comment by andreassiegel** [comment]
This sounds good! Thank you!

**Comment by CommonGuy** [comment]
This has been fixed in the latest beta version and will be released in the next stable version

**Comment by CommonGuy** [comment]
Kreya 1.15 has just been released.
