### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by azakharchenko-msol** [riok/Kreya#227]
**Describe the bug**
Opening kreya results blank screen
**To Reproduce**
run `snap install kreya` by default installs from latest/stable channel, the same issue seems on latest/edge

**Expected behavior**
Kreya is up and running
**Screenshots**
![image](https://github.com/riok/Kreya/assets/88085058/3b5e3c81-8a10-4bda-bbc3-afcbff581ecf)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Ubuntu 22.04
 - Kreya Version 1.14.0

**Additional context**
 logs
```
Gtk-Message: 10:07:06.664: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(kreya:1857781): Gtk-WARNING **: 10:07:06.716: GTK+ module /snap/kreya/215/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 10:07:06.716: Failed to load module "canberra-gtk-module"

(kreya:1857781): Gtk-WARNING **: 10:07:06.717: GTK+ module /snap/kreya/215/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 10:07:06.717: Failed to load module "canberra-gtk-module"

** (kreya:1857781): WARNING **: 10:07:08.023: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (kreya:1857781): WARNING **: 10:07:08.023: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 10:07:08.084: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(WebKitWebProcess:1857893): Gtk-WARNING **: 10:07:08.176: GTK+ module /snap/kreya/215/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 10:07:08.176: Failed to load module "canberra-gtk-module"

(WebKitWebProcess:1857893): Gtk-WARNING **: 10:07:08.177: GTK+ module /snap/kreya/215/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 10:07:08.177: Failed to load module "canberra-gtk-module"
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 600x672: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 600x672: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 600x672: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

** (WebKitWebProcess:1857893): WARNING **: 10:07:08.357: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:1857893): WARNING **: 10:07:08.357: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

** (WebKitWebProcess:1857893): WARNING **: 10:07:08.358: Failed to get atspi registered event listeners: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.452" (uid=1000 pid=1857893 comm="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWeb" label="snap.kreya.kreya (enforce)") interface="org.a11y.atspi.Registry" member="GetRegisteredEvents" error name="(unset)" requested_reply="0" destination=":1.2" (uid=1000 pid=4183 comm="/usr/libexec/at-spi2-registryd --use-gnome-session" label="unconfined")

**Comment by CommonGuy** [comment]
Very strange, I just tried this on Ubuntu 22.04 and it works for me.

Do you have any special configuration on your system?

**Comment by jmlara** [comment]
I'm getting a similar error running on Kubuntu 20.04.6 LTS .

(kreya:162753): Gtk-WARNING **: 15:18:01.633: Theme parsing error: gtk.css:1:21: Failed to import: Error opening file /home/jlara/snap/kreya/215/.config/gtk-3.0/colors.css: No such file or directory

** (kreya:162753): WARNING **: 15:18:01.746: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (kreya:162753): WARNING **: 15:18:01.746: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(WebKitWebProcess:162949): Gtk-WARNING **: 15:18:01.956: Theme parsing error: gtk.css:1:21: Failed to import: Error opening file /home/jlara/snap/kreya/215/.config/gtk-3.0/colors.css: No such file or directory
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 600x667: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 600x667: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 600x667: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

** (WebKitWebProcess:162949): WARNING **: 15:18:02.092: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:162949): WARNING **: 15:18:02.092: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

** (WebKitWebProcess:162949): WARNING **: 15:18:02.092: Failed to get atspi registered event listeners: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.44" (uid=1000 pid=162949 comm="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWeb" label="snap.kreya.kreya (enforce)") interface="org.a11y.atspi.Registry" member="GetRegisteredEvents" error name="(unset)" requested_reply="0" destination=":1.3" (uid=1000 pid=9654 comm="/usr/libexec/at-spi2-registryd --use-gnome-session" label="unconfined")


(WebKitWebProcess:162949): GStreamer-WARNING **: 15:21:16.346: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.

Is the latest/edge available via snap?

**Comment by CommonGuy** [comment]
Do you have a Nvidia GPU? Do any of the workarounds in https://github.com/wailsapp/wails/issues/2977 help?

**Comment by azakharchenko-msol** [comment]
The workaround helps! Thanks @CommonGuy 
running it as `WEBKIT_DISABLE_DMABUF_RENDERER=1 kreya` makes the trick and make it usable again :+1:

**Comment by jmlara** [comment]
I have a NVIDIA card.  The workaround works in Kubuntu 20.04.6 LTS as well.  Updated to WEBKIT_DISABLE_DMABUF_RENDERER=1 in /etc/environment file.

**Comment by CommonGuy** [comment]
Thanks for your feedback! I'll see whether we can solve this on our side in the future

**Comment by CommonGuy** [comment]
Thanks for your feedback. I added this information to our (newly created) FAQ: https://kreya.app/docs/faq/

**Comment by ruffsl** [comment]
Per the FAQ:

> If you are using snap, add the environment variable to /etc/environment.

Is there a better way to do this such that the env is specific to that one snap executable?
Or could we get regular Debian file instead? This snap stuff is a esoteric, and unpackaged tarballs are no better.

**Comment by CommonGuy** [comment]
We are currently working on Flatpak distribution, would that work for you? https://github.com/riok/Kreya/issues/64

**Comment by ruffsl** [comment]
A debian file would be preferred for me, but Flatpak distribution is probably nicer for other distro users.
