### ISSUE TITLE
View response metadata for gRPC calls

### ISSUE THREAD

**Issue by satazor** [riok/Kreya#236]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to view the response metadata for gRPC responses, only for requests.

**Describe the solution you'd like**
A Tab on the right side called "Metadata" so that we can view the metadata entries

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CommonGuy** [comment]
The response metadata is visible in the "Header" tab of the response:
![grafik](https://github.com/riok/Kreya/assets/8035999/a2e21fa3-949d-4da9-931b-0bfe81bfdfe8)
