### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Eitol** [riok/Kreya#25]
**Describe the bug**

**To Reproduce**
1. Go to 'About ->  Release channel (Select Beta)' (Version is show as 1.2.1
2. Clic to 'About ->  Check for update'
3- Restart
4-  (Version is show as 1.2.1

**Expected behavior**

**Screenshots**
 (Version is show as 1.2.1

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: macOS Big Sur (intel)
 - Kreya Version 1.2.1

I was downloaded, manually the beta version on
https://beta-downloads.kreya.app/Kreya-macos.zip
And this works

**Comment by latonz** [comment]
After you clicked 'Check for updates' can you see the message '1.3.0-beta.1 is ready to install' (or a loading spinner, indicating that the download is in progress)?
Is there an updates directory in `~/.config/Kreya`?

**Comment by Eitol** [comment]
'Check for updates' can you see the message '1.3.0-beta.1 is ready to install' 
Resp: Yes
![image](https://user-images.githubusercontent.com/1043061/113362942-f77a6a00-9325-11eb-9366-ce3202ad437a.png)

**Comment by Eitol** [comment]
A: 'Check for updates' can you see the message '1.3.0-beta.1 is ready to install'
R: Yes

A: "Is there an updates directory in ~/.config/Kreya?"
R: No. Only a file is in the directory (kreya.db)

**Comment by latonz** [comment]
We released `1.3.0.-beta.2`: if the update mechanism doesn't work for you, you can download it manually here: https://beta-downloads.kreya.app/Kreya-macos.zip. The checksum is available here: https://beta-downloads.kreya.app/appcast.json.

1.3.0-beta.2 improved logging during the upgrade process. Could you launch 1.3.0-beta.2, check for updates and check if there are any logfiles in `~/.config/Kreya`?

**Comment by CommonGuy** [comment]
Since we didn't hear back from you, we consider this issue resolved. Should this problem happen again, please comment and provide the log files from `~/.config/Kreya`
