### ISSUE TITLE
Formatted Response Pane doesn't respect dark mode on Mac

### ISSUE THREAD

**Issue by aoife9** [riok/Kreya#252]
**Describe the bug**
When sending a REST request the formatted response has a white background instead of the normal grey while in dark mode. If you toggle to raw the background will be dark mode, but switching back to raw goes back to a white background. 

**To Reproduce**
1. Send a REST request (GET, POST) where the expected content-type of the response is application/json
2. View the Formatted response
3. Toggle between Formatted / Raw

**Expected behavior**
The response pane should follow the theme for both raw and formatted responses. 

**Screenshots**
![Screenshot 2024-10-25 at 15 40 41](https://github.com/user-attachments/assets/d7c6de53-d6e0-4c44-a896-2735b9ba6a44)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: macOS Sonoma 14.7
 - Kreya Version 
 - {
  "kreyaVersion": "1.15.0",
  "releaseChannel": "stable",
  "osDescription": "Darwin 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:44 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_X86_64",
  "osVersion": "Unix 14.7.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "osx-x64",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}

**Additional context**

**Comment by CommonGuy** [comment]
Are you sure that the response Content-Type header is `application/json`? It looks like the response is interpreted as HTML, hence the Formatted response is rendered in an empty HTML document (this is where the white background comes from)

**Comment by aoife9** [comment]
Oh good idea, I double checked and it wasn't explicitly set as application/json on that endpoint. Changing that has resolved this!
