### ISSUE TITLE
Add option to open the File Explorer in the location of the krproj file.

### ISSUE THREAD

**Issue by coenm** [riok/Kreya#255]
**Is your feature request related to a problem? Please describe.**
I want to go to the folder where my projects is stored but i don't know how to.

**Describe the solution you'd like**
I would like to see a menu option to navigate to this location.

**Describe alternatives you've considered**
The project location in the status bar, clickable.

**Additional context**
empty.

**Comment by CommonGuy** [comment]
You can right-click any folder or operation in the operation list to view it in the file explorer:
![grafik](https://github.com/user-attachments/assets/bf7fc1f2-a459-44cb-a4ee-5884b2aee8c1)

It is also possible by right clicking an operation tab:
![grafik](https://github.com/user-attachments/assets/7e4aadd4-5953-4c4c-a7e3-269c8777fa88)

**Comment by coenm** [comment]
Yes, thanks!
