### ISSUE TITLE
"Natural" rendering for output in raw string

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#269]
Hello, 

I am querying on an API endpoint that produces a plain text string response.
In .Net the method is declared like this : 
    [ProducesResponseType(typeof(string), StatusCodes.Status200OK, MediaTypeNames.Text.Plain)]
I ran the "importer" in my Kreya project to have access to the method.

In Response panel, with "Raw" mode selected, the output looks like this : 
![image](https://github.com/user-attachments/assets/68319cf9-3202-457b-9e8b-7cb8da8ecf9a)
![image](https://github.com/user-attachments/assets/0ae94e99-6763-40ec-a144-37f495bdbac3)

Instead I would like to see the "human friendly" equivalent, **especially with \r\n rendered as line breaks**. 

Could you please add in Response a such like feature next to Formatted and Raw ?

Additionnally, if I do "Save to file", the extension suggested for the file is Json even in "Raw" mode, and the line breaks are not rendered either. I'm not sure if it comes from Kreya itself or if I have something else to do to produce raw text.

Thank you

**Comment by CommonGuy** [comment]
Could you show what the response headers are? Kreya tries to infer the content type from those

**Comment by AFract** [comment]
I'm sorry, I have just figured the problem : if I use "return Content(notesAsText, "text/plain");" it's ok. 
The controller was using "return Ok(text)", so the response headers were wrong. Probably "Ok()" always assume the content is always an object, even it a string was supplied. 
You can close the ticket, i'm sorry for annoyance

**Comment by AFract** [comment]
PS : and as always, thanks for your incredible speed in responding !

**Comment by CommonGuy** [comment]
Yes, as far as I know "Ok(...)" always produces JSON content type headers.

You're welcome, we are always happy to receive bug reports such as yours with that many details!
