### ISSUE TITLE
Request does not support int64 numbers

### ISSUE THREAD

**Issue by agorea** [riok/Kreya#28]
Tried to make a gRpc request having a long number inside the request, like the credit card number, but I received the error: Error starting gRpc call. An error occurred while sending the request, Invalid operation exception: Did not write as much data as expected.

Freya version 1.3.1 for windows 10 x64

To reproduce this issue, you need to have a request that needs an int64, eg. 
message LargeNumber {
    int64 number = 1;
} 

Try to send this request to an endpoint, the error is received.

**Comment by CommonGuy** [comment]
Thanks for the bug report. Indeed, int64, sfixed64 and sint64 values aren't correctly serialized to the wire if you use huge values. We're going to fix this as soon as we can.

**Comment by CommonGuy** [comment]
We released a fix for this on our Beta release channel. You can switch to the beta version by either changing the release channel in the app via Kreya -> About -> Release Channel -> Select "Beta" -> then Check for Updates. Or manually install the Beta version from https://beta-downloads.kreya.app/Kreya-win.msi (uninstall the current Kreya version first, no data will be lost).

The fix will be included in the v1.4.0 stable release of Kreya.

**Comment by latonz** [comment]
BugFix is released with Kreya 1.4.
