### ISSUE TITLE
Server stream results not scrollable/expandable

### ISSUE THREAD

**Issue by EAPR** [riok/Kreya#32]
A server stream with more responses that can fit in the response area cannot be scrolled and the individual messages cannot be expanded either.

![image](https://user-images.githubusercontent.com/19491066/115402415-662a4500-a1b9-11eb-8bc4-e23a0344aeaf.png)
 - OS: Windows 10
 - Kreya Version 1.4.0-beta.2

**Comment by CommonGuy** [comment]
Thank you for reporting this bug, it is on our radar. Sadly, due to the layout and a bug in our editor dependency, this bug is a little difficult to fix. We are working on it and we will let you know when it has been fixed.

**Comment by EAPR** [comment]
Any estimates on when this could be solved?

**Comment by CommonGuy** [comment]
Sadly, I cannot give an exact date when this will be solved. We managed to fix it on Windows, but the Mac OS version is still a little buggy. As soon as we resolve the outstanding bugs, we'll release a beta version and inform you about the progress. Sorry that this is taking a little longer!

**Comment by CommonGuy** [comment]
Kreya v1.5 was just released, which includes a fix for this bug.
