### ISSUE TITLE
Text looks blurry on a 4K monitor

### ISSUE THREAD

**Issue by nazar554** [riok/Kreya#33]
**Describe the bug**
Due to poor DPI scaling Kreya app text looks blurry on a 4K display.
**To Reproduce**
1. Get a 4K monitor
2. Set scaling to 150%
3. Start Kreya

**Expected behavior**
Text inside Kreya should look sharp like in all other apps.

**Screenshots**
Comparison with Visual Studio
![screenshot](https://user-images.githubusercontent.com/12029825/117356701-b6ddb580-aebc-11eb-8c5c-1abe2c28a75c.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 10 20H2 19042.928
 - 27' 3840x2160 4K primary monitor with scaling set to 150% (the default value, not custom scaling), 1080p secondary monitor (scaling also set to 150%)
 - Kreya Version: 
```
{
  "kreyaVersion": "1.4.0",
  "platform": "Win32",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.51"
}
```

**Comment by CommonGuy** [comment]
We just released Kreya 1.5.0-beta.1 which includes this bugfix: https://kreya.app/release-notes/beta. You can switch to the Beta release channel in the app via Kreya -> About. Change the release channel to Beta and search for updates. It should then install the newest Beta version. Please note that the Beta channel may contain some unstable features.

**Comment by nazar554** [comment]
Yep, it look fine now. Thanks!

**Comment by CommonGuy** [comment]
Kreya v1.5 was just released, which includes a fix for this bug.
