### ISSUE TITLE
Fake data generation template placeholders

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [riok/Kreya#41]
**Is your feature request related to a problem? Please describe.**
It's cumbersome having to come up with sensible values for various properties of calls (names, birthdates, addresses, etc...)

**Describe the solution you'd like**
Back in the day (😜) when I was still writing REST API services, I would use postman to test various calls, which allowed me to use  'Dynamic variables' ([link to their docs](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/)) to define placeholders for various commonly used property types like names, addresses, dates, guids, etc.... By writing the body of an API call using these variables, I could just make the call multiple times and having a unique record created every time.

I assume they're using the popular 'Faker' library, which is readily available in all kinds of languages (see e.g. Bogus or Faker.Net for .NET).

It would be great if we could have this in Kreya as well.

**Describe alternatives you've considered**
None

**Comment by latonz** [comment]
Thank you for your feature request. We do have this on our roadmap and plan to implement this soon(ish). We'll keep this issue updated about any progress.

**Comment by CommonGuy** [comment]
This has been released with Kreya 1.7.
