### ISSUE TITLE
Enable change to maximum message sizes

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [riok/Kreya#45]
**Is your feature request related to a problem? Please describe.**
Currently we can't modify the maximum message size for GRPC messages. I have several calls which transfer binary objects (e.g. PDFs) which might be larger than the default limit of 4Mb, these calls can currently not be tested with Kreya :(

**Describe the solution you'd like**
One option would be to remove the limit altogether, but a setting somewhere that allows to configure it would allow to test both situations.

**Describe alternatives you've considered**
BloomRPC doesn't support this either (as far as I can see at least). So the only alternative really is to write my own GRPC client, in .NET 5, the incoming message limit can be configured as follows:
```csharp
services.AddGrpcClient<<client type>>(o =>
{
    o.Address = new Uri(<url>);
})
.ConfigureChannel(o =>
{
    o.MaxReceiveMessageSize = 1024 * 1024 * 50;
});
```

**Comment by CommonGuy** [comment]
Shouldn't be hard to add this as a setting, we will add this soon.

**Comment by CommonGuy** [comment]
This feature will be included in the upcoming v1.6 release. You can already try it out in the 1.6.0-beta.1 version by switching the release channel in the About window and checking for updates. Note that the beta version may contain bugs.

**Comment by CommonGuy** [comment]
V1.6 has been released.

**Comment by AlexGoris-KasparSolutions** [comment]
Confirmed working, thanks a bunch!
