### ISSUE TITLE
Importer endpoint templateable

### ISSUE THREAD

**Issue by MichalSimara** [riok/Kreya#46]
**Is your feature request related to a problem? Please describe.**
I have different environments that are configured to use different endpoint. I would like to configure importer to use same endpoint that is used by current environment for requests.

**Describe the solution you'd like**
I am able to define custom variable for endpoint in environment data 
```
{
  "endpoint": "grpc-endpoint-url"
}
```
and templating feature in settings endpoint field {{endpoint}}. When I am trying to use this template to configure importer endpoint I'll get invalid URL error. 
It would be great when templating will be supported also by importer endpoint field.

**Comment by CommonGuy** [comment]
Great idea, we'll implement this in the next version of Kreya.

**Comment by latonz** [comment]
We released this feature on our Beta-channel: https://kreya.app/docs/release-notes/beta. You can switch to the Beta release channel in the app via Kreya -> About. Change the release channel to Beta and search for updates. It should then install the newest Beta version. Please note that the Beta channel may contain some unstable features.

We expect to release this feature in the stable version of Kreya in the next 1-3 weeks.

**Comment by CommonGuy** [comment]
This has just been released with Kreya 1.7.
