### ISSUE TITLE
Reference Token with Scriban variable

### ISSUE THREAD

**Issue by uschwag** [riok/Kreya#49]
**Is your feature request related to a problem? Please describe.**
When creating a collection or request we can use an Authentication which gets a Token, e.g. from Keycloak,
and exposes it in the Kreya GUI as an Access-Token, see Screenshot.
In our cases this has to be provided to the service by a JSON tag, e.g. 
"token": "the Access-Token"
The first idea was to try to reference it as a variable
"token": "{{Access-Token}}"
but that doesn't work.

**Describe the solution you'd like**
Kreya should have some kind of system variables for such kind of information, that we can reference in requests.

**Describe alternatives you've considered**
It could even be an idea that user can set it to a variable himself in a kind of post request script related to the Auth request send by the Authentication.

**Additional context**
Add any other context or screenshots about the feature request here
![Kreya_Access_Token](https://user-images.githubusercontent.com/91600653/135292363-484381de-22ff-43b3-a3fb-be06d04d23f2.jpg)
.

**Comment by CommonGuy** [comment]
This is definitely something we plan to implement.

**Comment by uschwag** [comment]
Just recognised the feature "make auth configurations available through scriban templating" in the 1.7-alpha.3 version. Is that already covering my request? How can I test it?

**Comment by latonz** [comment]
You are correct, we implemented this feature in kreya 1.7-alpha.3 😊.
However, we just released a new version on the Beta-channel of kreya: https://kreya.app/release-notes/beta. You can switch to the Beta release channel in the app via Kreya -> About. Change the release channel to Beta and search for updates. It should then install the newest Beta version. Please note that the Beta channel may contain some unstable features.

We expect to release this feature in the stable version of Kreya in the next 1-3 weeks.

With this feature it is possible to reference auth configs from request bodies and headers by using scriban templating. For example if you have a basic auth config named `My Auth` you can access it's computed value via `{{ auth.configs.my_auth.value }}` (note the slugified name). This also works with auth configurations of other types.

If you need further assistance or want to provide us some feedback, don't hesitate to leave a comment.

**Comment by uschwag** [comment]
Thanks a lot for implementing the possibility to reference auth configs . It works fine.
Do you already have a guess when we can get data from the request body to put it to a variable (like is is possible in Postman?
Currently I do this manually but I saw it on your roadmap.

**Comment by latonz** [comment]
We track this in https://github.com/riok/Kreya/issues/23. We just increased it's priority internally due to popular demand. You may add a 👍  reaction to issues you would like to see prioritised.

**Comment by CommonGuy** [comment]
Kreya 1.7 has just been released, with support for referencing authentication configurations.
