### ISSUE TITLE
Implementing an RPC Library

### ISSUE THREAD

**Issue by ropacz** [riok/Kreya#51]
Hello, how is everything?

I would like to know if it is possible to implement Kreya for a new library called sdkgen ?

You can have more information about this library at the links below:

https://github.com/sdkgen/sdkgen/

https://sdkgen.github.io/ (documentation in Portuguese)

It was created by a team of qualified professionals, and serves different platforms (dart, dotnet, kotlin, typescript etc).

I'm waiting for an answer. Thanks!

**Comment by CommonGuy** [comment]
Hi and thanks for the inquiry. We do not plan to implement sdkgen
