### ISSUE TITLE
Selectable error message during setup

### ISSUE THREAD

**Issue by Thijxx** [riok/Kreya#52]
**Is your feature request related to a problem? Please describe.**
During Initial project setup, if an error is produced it disappears after a few seconds. I'd like to read the message.
Also I cannot select/copy the message. I need to share the message, with this ticket for example.

**Describe the solution you'd like**
Keep error on screen, make selectable.

**Comment by CommonGuy** [comment]
Starting with Kreya 1.7, the error message is shown longer and selectable.
