### ISSUE TITLE
.. referenced but not found

### ISSUE THREAD

**Issue by Thijxx** [riok/Kreya#54]
**Describe the bug**
The error message telling me that something is referenced but not found should tell me where it is referenced.
This happens during initial project setup.

**To Reproduce**
1. Create new project
2. Import gRPC with "for Kreya faulty" reference

**Expected behavior**
Message like: in filename.proto this filename.proto is referenced and it is not found.

**Comment by CommonGuy** [comment]
Kreya 1.7 has just been released with an improved error message for this scenario.
