### ISSUE TITLE
Application crashes upon launch on MacOS

### ISSUE THREAD

**Issue by pavelterex** [riok/Kreya#57]
**Describe the bug**
Application crashes upon launch on MacOS (see stacktrace.txt for details)

**To Reproduce**
1. Launch Kreya.app

**Expected behavior**
Application started

Stacktrace: [stacktrace.txt](https://github.com/riok/Kreya/files/7482258/stacktrace.txt)

**Comment by latonz** [comment]
Thanks for the bug report.

The following information would be interesting to us:

1. Does the ~/.config/Kreya folder exist?
1. Is there a Kreya.db file in there?
1. Could you try to launch the app via terminal with the following command (if the kreya app is located in /Applications): `KREYA_LOGGING_LEVEL=Information /Applications/Kreya.app/Contents/MacOS/Kreya.app`.
3.1 Are there any errors reported to stdout/stderr?
3.1. Is there a log file in ~/.config/Kreya? Could you paste the contents of these files into this issue?

PS: To add stack traces and other large contents you can use `<details><summary>[Title]</summary>[Contents]</details>` inside github issues. This displays the content in a collapsible which keeps the issue more readable.

**Comment by pavelterex** [comment]
> Does the ~/.config/Kreya folder exist? 

no such folder

> Could you try to launch the app via terminal with the following command (if the kreya app is located in /Applications): KREYA_LOGGING_LEVEL=Information /Applications/Kreya.app/Contents/MacOS/Kreya.app. Are there any errors reported to stdout/stderr?

pavel.terekhov@pavel Downloads % KREYA_LOGGING_LEVEL=Information /Applications/Kreya.app/Contents/MacOS/Kreya.app
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Users/pavel.terekhov/.config/Kreya' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Kreya.Data.FileSystem.FileService.EnsureDirectory(String path)
   at Kreya.Data.DbInitializer.EnsureDbDirectoryExists()
   at Kreya.Data.DbInitializer.Initialize()
   at Kreya.UI.UiServices.AppUiServices.RunApp(String project)
   at Kreya.UI.Program.Main(String[] args)
zsh: abort      KREYA_LOGGING_LEVEL=Information 

> Is there a log file in ~/.config/Kreya? Could you paste the contents of these files into this issue?

not present

**Comment by latonz** [comment]
Kreya stores data in `~/.config/Kreya`. If this directory does not exist, kreya tries to create it. In your case, the creation of this directory fails due to `Permission denied`. Do you have special permission control in place? Could you try to create this directory manually and try to launch kreya again?

**Comment by pavelterex** [comment]
It appears that ownership of ~/.config folder had been accidentally changed to a 'system' user (have no idea when and by whom though)
After I got back my ownership of the folder Kreya.app works pretty fine
Sorry for inconvenience

**Comment by latonz** [comment]
No worries, happy we could resolve the issue 😊

**Comment by pavelterex** [comment]
Btw, perhaps in such case app should have more clear error thrown?

**Comment by latonz** [comment]
Definitely the user should be better informed about this. We will certainly improve this. An internal tracking issue exists already.
