### ISSUE TITLE
Deadline setting

### ISSUE THREAD

**Issue by malyginvv** [riok/Kreya#58]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to set a deadline for unary RPC.

**Describe the solution you'd like**
Deadline setting at method level and/or at folder level.

**Describe alternatives you've considered**
I've tried to add metadata with a key "grpc-timeout" and a value of "1S" as per gRPC protocol specification, but it looks like the client ignores this header completely. There was no metadata with key "grpc-timeout" on the server side when I called a method. Other metadata keys work just fine, only "grpc-timeout" is ignored.

**Additional context**

**Comment by CommonGuy** [comment]
This is a peculiarity in the .NET gRPC implementation we use, as it expects the deadline via other options than the header. We'll fix this, so that the deadline can be set via the "grpc-timeout" header.

**Comment by EraYaN** [comment]
Bespoke UI might also not be a bad idea, since then you can give some nice (preset?) UI options as a helping hand to users.

**Comment by latonz** [comment]
V1.8 has been released.
