### ISSUE TITLE
UI freezes in a blank screen when creating a project

### ISSUE THREAD

**Issue by nickaein** [riok/Kreya#60]
**Describe the bug**

Kreya UI freezes when creating a new project (as shown in screenshot). I've tried reinstalling it (with snap) but the problem is still present. I've also cleared the content of following paths to have a clean installation:

~/snap/kreya
~/kreya

**To Reproduce**
1. Start Kreya
2. Click on '+ Create Project...'
3. Kreya stucks at a blank screen

**Expected behavior**
Kreya should show the next steps for setting up the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/8047027/141158415-df920747-c1ee-4f4e-90bf-63273a4e246e.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Ubuntu 20.04.3 LTS
 - Kreya Version 1.7.0

**Additional context**

It seems the UI freezes even when I try to copy the version number from "About" page using the "copy" button.

**Comment by CommonGuy** [comment]
Strange, creating a project in Ubuntu 20.04.3 works for me... Are you sure that you installed the 1.7.3 Kreya version? The latest stable version should be 1.7.0 when you install via `snap install kreya`.

The following information would be interesting to us:
1. Could you try launching Kreya from the terminal via `KREYA_LOGGING_LEVEL=Information kreya`?
2. Are there any errors reported to stdout/stderr?
3. Could you paste the contents of `~/snap/kreya/current/.config/Kreya/kreya.log`?

**Comment by latonz** [comment]
Since there was no feedback, we consider this bug report closed. Should the bug still exist in the current Kreya version, please comment with more information and reopen this issue.

**Comment by nickaein** [comment]
Sorry for not updating this issue. A simple reboot fixed the problem. There was some instability in device drivers (sound device AFAIK) which was causing the problem and is probably out of the scope of Kreya project.

**Comment by latonz** [comment]
Thank you for your response, glad that the problem is now fixed 😊
