### ISSUE TITLE
Telemetry logs in request trace

### ISSUE THREAD

**Issue by TrueCarry** [riok/Kreya#63]
**Describe the bug**
Telemetry logs appear in request trace

**To Reproduce**
1. Make streaming request
2. Wait (around 5 minutes?)

**Expected behavior**
Only my request trace is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/5431520/142209534-ab30bd6c-39e5-44e4-be48-ed88d93e4151.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - Windows 10
 - 1.7.0

**Comment by CommonGuy** [comment]
Thank you for reporting this bug. The problem is that our tracing implementation is "global", meaning it intercepts all HTTP calls made by Kreya. This should definitely be fixed, so that only the correct traces show up.

This is also a prerequisite for #55.
