### ISSUE TITLE
gRPC-Web header authentication

### ISSUE THREAD

**Issue by optiman** [riok/Kreya#65]
**Is your feature request related to a problem? Please describe.**
I need to be able to provide gRPC-Web authentication info inside `Cookie` HTTP request header.

**Describe the solution you'd like**
Add additional Authentication Type `HTTP headers` with ability to add custom HTTP headers for gRPC-Web requests.

**Describe alternatives you've considered**
There is no alternative for working with cookie-based auth in Kreya at the moment.

**Comment by CommonGuy** [comment]
This should already be supported in Kreya via templating. Could you try adding a "Cookie" entry in the request metadata with the value `your-cookie-name={{ auth.configs.your_auth_name.value }}`?

**Comment by optiman** [comment]
Isn't the point of `Authentications` configuration being able to configure once and use this auth type for every request in the environment?
And using `{{ auth.configs.your_auth_name.value }}` (from, let's say `Basic` auth type) as a value for metadata entry is not possible, because then the header is generated as:
```
[metadata_key]: base64(auth_username:auth_password)
``` 
I managed to send the Cookie header as Metadata by adding it's value to Environment Data, and then using `{{ env.CookieValue }}` as Metadata value. But then I need to manually add this Metadata key to every single request, that needs authentication - not very user-friendly, in my opinion.

Why not add a separate Authentication type to set up this cookie header and being able to quickly switch it inside environment with a dropdown in Auth tab?
As a use case - testing multiple users with different permissions.
If you have a hundred different gRPC methods and need to debug different user types - you need to manually change the Metadata text fields in every request or create a whole separate environment for every user type that is expected to receive different responses.

**Comment by CommonGuy** [comment]
In our opinion, Authentications are used to handle an "authentication state". For example, OIDC can be used to fetch a token or basic auth to transfrom a username and password into `base64(auth_username:auth_password)`. The Authentications do not define how these values are sent, that happens via the protocol default mechanism. In case of gRPC, via the Authorization metadata (=HTTP header). For everything else, templating should be used to inject the "authentication state" into the desired place.

We currently have no explicit support for Cookies, as their usage is rather unusual for gRPC. Simply creating an authentication type "Cookie" wouldn't solve this problem cleanly, as users may want to send multiple cookies or cookies which aren't authentication related.

For your use case, do you know about https://kreya.app/docs/default-settings? With the default settings, you can set Metadata entries for all requests in a folder or even in the entire project. That allows you to choose different approaches to your problem, whichever suits you best:
- Create a folder for each user and duplicate the desired requests into each folder. Then set a different cookie Metadata entry for each folder
- Create a different environment for each user and set the Metadata to something like `{{ env.CookieValue }}`. To switch users, simply switch the environment.
- Keep a single folder, set a static cookie value in the Metadata. To switch users, simply edit the Metadata for that folder

**Comment by optiman** [comment]
I guess I will need to create a separate environments for every user and set auth Metadata in Default settings to be able to quickly switch the user with a dropdown.
Not ideal from the UX point of view, but usable, unlike other gRPC GUI clients.
Thank you.

**Comment by CommonGuy** [comment]
Thanks for the compliment! 😊 We realize the solution is not 100% optimal for you. We'll keep you updated if we implement something (ex. nested or base environments) that improves this use case.
