### ISSUE TITLE
Copying the error text from the response

### ISSUE THREAD

**Issue by rchkv** [riok/Kreya#68]
**Is your feature request related to a problem? Please describe.**
I want to copy the error text when my request is broken, so that I can attach it to the bug, for example. I'm afraid now it's impossible. 

**Describe the solution you'd like**
Double-click for copying or right-click for context menu open.

**Additional context**

![Screenshot 2021-12-16 at 09 57 16](https://user-images.githubusercontent.com/18264667/146311198-188c09d9-10c8-446c-a8db-3e7c88fd721b.png)

**Comment by CommonGuy** [comment]
Thanks for reporting this, we'll make the text selectable or provide another mechanism for copying that text.

In case you didn't know, you can view the full text by hovering over it with your mouse.

**Comment by latonz** [comment]
V1.8 has been released and implements an option to copy the text.
