### ISSUE TITLE
Expect UTF-8 support when returning a response

### ISSUE THREAD

**Issue by GuoXingyou** [riok/Kreya#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by latonz** [comment]
This looks like a duplicate of https://github.com/riok/Kreya/issues/62. You can try the workaround described in https://github.com/riok/Kreya/issues/62#issuecomment-967105012 until the bugfix is released.

Closing as duplicate, feel free to reopen if the workaround doesn't work for you.

**Comment by GuoXingyou** [comment]
thanks
