### ISSUE TITLE
Support Apple Silicon (M1)

### ISSUE THREAD

**Issue by CommonGuy** [riok/Kreya#7]
**Is your feature request related to a problem? Please describe.**
Kreya currently doesn't support Apple Silicon.

**Describe the solution you'd like**
Kreya should provide an installer for Apple Silicon.

**Additional context**
Awaiting .NET support: https://github.com/dotnet/runtime/issues/43313

**Comment by klipach** [comment]
Looks like .NET issue was resolved

**Comment by latonz** [comment]
We are currently waiting for our M1 hardware to arrive and will soon start implementing this.

**Comment by jetrinh-dd** [comment]
Hi there! Wanted to check in on this. Is support available for M1 macs now? I see the label changes on this PR but it looks like the [Getting Started](https://kreya.app/docs/getting-started/) doc still says M1 is not supported?

**Comment by CommonGuy** [comment]
The stable 1.8 release isn't quite ready yet. If you want to try Kreya for M1 already, we just released a beta version which you can download here: https://beta-downloads.kreya.app/Kreya-macos-arm64.zip.

Please note that this beta release may contain bugs. Once the stable version is ready, you can switch to the stable version channel without any problems.

**Comment by latonz** [comment]
M1 support has been released with V1.8.
