### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FlymeDllVa** [riok/Kreya#70]
What license does the project have? Will there be access to the code?

**Comment by CommonGuy** [comment]
As stated in https://github.com/riok/Kreya/issues/21, Kreya isn't currently open source. We will add this and our reasons for not open-sourcing Kreya to our documentation

**Comment by CommonGuy** [comment]
As stated in our blog post https://kreya.app/blog/why-kreya-isnt-open-source, Kreya isn't open source.
