### ISSUE TITLE
Can't copy the StackTrace when the Kreya request fails

### ISSUE THREAD

**Issue by k3rne1pan1c** [riok/Kreya#71]
**Describe the bug**
Whenever we do a request, we can't copy the StackTrave.

**To Reproduce**
1. Do a request that fails
2. Try to copy the strack trace
 
**Expected behavior**
Right click + Copy , or just click on it and get a representation of the error where you can copy it as well.

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Ubuntu LTS
 - Kreya Version: 1.7

**Comment by CommonGuy** [comment]
Hi and thanks for your bug report. This looks like a duplicate of https://github.com/riok/Kreya/issues/68. Or do you have another problem?

**Comment by CommonGuy** [comment]
Closing as duplicate, feel free to reopen if your issue is different from the linked issue.
