### ISSUE TITLE
Better handling of removed RPCs

### ISSUE THREAD

**Issue by maximg** [riok/Kreya#81]
**Is your feature request related to a problem? Please describe.**
When an RPC is removed from the service definition, it remains visible in Kreya.

This makes sense: when switching between API branches where the RPC is present / removed, I would like to keep request contents available. However, it will help if Kreya provides a method to clean up removed RPCs when they are not interesting to me anymore.

**Describe the solution you'd like**
I would like a mechanism which removes all RPCs which are not present in proto files. This should be a manual action.

**Describe alternatives you've considered**
There are a few alternatives:
 1. **Automatically delete such RPCs.** As mentioned above, it breaks a typical development workflow, though versioning of Kreya folder may fix most of the issues here.
 2. **Highlight deleted RPCs.** They can be then deleted individually. This also could be a viable option as RPCs are removed quite rarely.

**Comment by CommonGuy** [comment]
Thanks for you feature request. Highlighting deleted RPCs or providing a custom dialog to remove them are probably the way to go. We added this to our roadmap, but I cannot yet say by when this will be implemented.
