### ISSUE TITLE
Add tabs for recently used RPCs

### ISSUE THREAD

**Issue by sulfax** [riok/Kreya#87]
**Is your feature request related to a problem? Please describe.**
I often switch between RPC calls, and sometimes need to make the same call twice. It a bit annoying that I need to scroll between thousands of RPC to find the one i recently used, as well as needing to store the request message somewhere outside Kreya if I need to send a different message and then go back to the previous one. 

**Describe the solution you'd like**
Doubleclicking a RPC should open a new tab for that RPC. Single clicks can work the same way it does. This could store messages for later and reusage in an efficiant way

**Comment by CommonGuy** [comment]
Thank you for your feature request. We plan to implement this and added it to our backlog.

**Comment by CommonGuy** [comment]
Kreya 1.10 has just been released with support for this feature.
