### ISSUE TITLE
Unable to copy value in response header/trailer tab

### ISSUE THREAD

**Issue by hondasmx** [riok/Kreya#94]
**Describe the bug**
Unable to select/copy header value in response header/trailer tab

**To Reproduce**
1. Make a grpc request that return any headers
2. Try to select the text inside header/trailer tab
3. The text is not selectable and because of that I can't copy the values from it

It worked in previous versions (1.7.*) on both mac/win

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: MacOS 12.4, Win10
 - Kreya Version 1.8.0

<img width="540" alt="image" src="https://user-images.githubusercontent.com/7237169/179508516-764df5ac-4e9a-4623-9e8c-ac3e879a6c75.png">

**Comment by CommonGuy** [comment]
Thanks for your bug report. We'll fix this bug in the next release.

**Comment by CommonGuy** [comment]
We released a fix for this on our alpha and beta channels. To use it, open the "About" window in Kreya and switch to the "Beta" channel, then check for updates.

**Comment by hondasmx** [comment]
Thanks a lot. It works!

**Comment by CommonGuy** [comment]
The bugfix has been released on the stable channel with version 1.8.1.
