### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by benjamin-lang** [riok/Kreya#95]
**Describe the bug**
Trying to install the Kreya-win.msi in an enterprise environment for evalation of software features. While the installation runs, it has stopped and rollbacked afterwards.

**To Reproduce**
1. Download the installer Kreya-win.msi 
2. Install

**Expected behavior**
Successful installation

**Screenshots**
![install_error](https://user-images.githubusercontent.com/36487661/179696950-d6d931ae-bb3d-4296-90c0-dcc27693b226.PNG)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 10
 - Kreya App Version: Created on 11.07.2022
 - Installer Revision: {E387A920-B5EE-4509-AC8A-0E7A2CFE3AFA}

We would like to evaulate the softwarefeatures in order to decide if we should use the software.

Help is very much appreciated.

**Comment by CommonGuy** [comment]
Hi and sorry that Kreya isn't installing correctly on your system. Could you share any relevant Windows Event Log entries? I suspect the error is related to the WebView2 detection/installation.

Is the [WebView2 runtime](https://developer.microsoft.com/en-US/microsoft-edge/webview2/) installed?  If yes, is it on a per-user or per-machine basis? If it is not installed, the Kreya setup tries to download and install the WebView2 bootstrapper, which requires an internet connection.

**Comment by benjamin-lang** [comment]
@CommonGuy Thanks for the quick response, you are right about the reason:

![event_log](https://user-images.githubusercontent.com/36487661/179739964-95100f30-7b1d-4341-874e-edd1b17863d4.PNG)

I will ask our software department if can install it. I will get back to you.

**Comment by benjamin-lang** [comment]
After downloading and installing the webview installer and restart of my system the application works. Thanks for your help. Now I have an api connection problem and i will open a new question.

**Comment by CommonGuy** [comment]
Thanks for your update, happy that it worked for you. I'll keep this issue open, as we plan to improve the setup and installation of WebView2 a bit.

**Comment by CommonGuy** [comment]
We improved the Windows installer, which will hopefully prevent issues such as this one
