### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by vickyzhuang** [riok/Kreya#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: [e.g. Windows 10]
 - Kreya Version [e.g. 1.0.0-beta.3]

**Additional context**

**Comment by CommonGuy** [comment]
As the bug report has been left empty, I'm going to close this issue.
